name: CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        scala: [3.2.0]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 18
          check-latest: true

      - name: Coursier cache
        uses: coursier/cache-action@v6

      - name: Check formatting
        run: sbt fixCheck
      - name: Compile and test
        run: sbt test
